swagger: '2.0'
info:
  title: Automatized Fisher Brand Shaker API
  version: "0.1"
  description: API to execute operations on shaker
consumes:
  - application/json
produces:
  - application/json
paths:
  /status:
    get:
      tags: [status]
      operationId: shaker.status
      summary: Queries for status
      responses:
        200:
          description: Return response
          schema:
            $ref: '#/definitions/RobotResponse'

  /is_ready:
    get:
      tags: [is_ready]
      operationId: shaker.is_ready
      summary: Queries for ready status
      responses:
        200:
          description: Return response
          schema:
            $ref: '#/definitions/RobotResponse'
        404:
          description: Some kind of error, verbose output should be attached
  /start:
    get:
      tags: [start]
      operationId: shaker.start
      summary: Starts shaker
      responses:
        200:
          description: Return response
          schema:
            $ref: '#/definitions/RobotResponse'
        404:
          description: Some kind of error, verbose output should be attached

  /stop:
    get:
      tags: [stop]
      operationId: shaker.stop
      summary: Stops shaker
      responses:
        200:
          description: Return response
          schema:
            $ref: '#/definitions/RobotResponse'
        404:
          description: Some kind of error, verbose output should be attached


parameters:

definitions:
  RobotResponse:
    type: object
    required:
      - stdout
      - response_code
      - description
    properties:
      stdout:
        type: string
        description: Complete backend stdoutput/stderror from command
        example: "Execution successful OK"
        readOnly: true
      response_code:
        type: string
        description: The response code number
        example: "43"
        minLength: 1
      description:
        type: string
        description: Response described in cleartext
        example: "Busy"
        minLength: 1

#security:
#  # enable OAuth protection for all REST endpoints
#  # (only active if the TOKENINFO_URL environment variable is set)
#  - oauth2: [uid]

#securityDefinitions:
#  oauth2:
#    type: oauth2
#    flow: implicit
#    authorizationUrl: https://example.com/oauth2/dialog
#    scopes:
#      uid: Unique identifier of the user accessing the service.
